FROM microsoft/dotnet:2.2-sdk

RUN apt-get update \
    && apt-get install -y \
       zip \
       curl \
       emacs-nox \
       git \
       man-db \
       manpages \
       htop \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /git
RUN git clone https://github.com/jeremymeng/dotfiles.git dotfiles
RUN ls -al .
RUN find dotfiles -maxdepth 1 -type f
RUN find dotfiles -maxdepth 1 -type f | xargs -I {} cp {} ~/
